# Generated by Django 2.1.3 on 2018-12-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(default='', max_length=200),
        ),
    ]
