# Generated by Django 2.1.3 on 2019-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_mineral_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='group',
            field=models.CharField(max_length=200),
        ),
    ]
